config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root 'articles#index'
  resources :users, only: [:show]
  resources :groups, only: [:index, :show, :create] do
    member do
      get :api, defaults: { format: 'json' }
    end
  end
  resources :comments, only: [:create]
  resources :favorites, only: [:create] do
    collection do
      post :api, defaults: { format: 'json' }
    end
  end
  resources :articles, only: [:index, :show] do
    resources :article_comments, only: [:index, :show, :create] do
      collection do
        get :index10
        get :api, defaults: {format: 'json'}
      end
    end
  end
  resources :evaluations do
    collection do 
      post :good
      post :bad
      post :canceling_good
      post :canceling_bad
    end
  end
end

app/models/article_comment.rb
class ArticleComment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  has_many :evaluations, dependent: :destroy
  has_many :article_comment_replies

end

app/controllers/article_comments_controller.rb
class ArticleCommentsController < ApplicationController
  before_action :set_params
  before_action :set_anchors, only: [:create, :api]
  before_action :find_comments, only: [:index, :index10]
  before_action :find_articles, except: [:create, :api]

  def index
    @article_comments = ArticleComment.new
  end

  def index10
    @comments = @comments.order("created_at DESC").limit(10).reverse
    @article_comments = ArticleComment.new
  end

  def show
    @comment = ArticleComment.find(params[:id])
    @article_comments = ArticleComment.new

  end

  def create
    posted_comment = ArticleComment.create(comments_params)
    length = ArticleComment.where(article_id: @article_id).length
    posted_comment.update(index: length.to_i)
    parent_id = posted_comment.id
    anchors1 = posted_comment.text.scan(/(?<=\>>)\d+/).uniq
    if anchors1[0].present?
      anchors1.each do |a|
        children = ArticleComment.find_by(article_id: @article_id, index: a)
        children_id = children.id
        ArticleCommentReply.create(parent_article_comment_id: parent_id,
                                   children_article_comment_id: children_id)
      end
    end
    @new_comment = ArticleComment.includes(:user).where('article_id = ? and id > ? and id <= ?', 
                                                        @article_id, @last_comment_id, posted_comment.id)

    @new_comment.each do |c|
      arrayAnchors(c, @anchors)
      userDistinction(c, @userDistinction)
    end
    respond_to do |format|
      format.html { redirect_to article_article_comments_path(@article_id)}
      format.json
    end
  end

  def api

    if @last_comment_id == nil
      @comments = ArticleComment.where(article_id: @article_id)
    else
      @comments = ArticleComment.where('id > ? and article_id = ?', @last_comment_id, @article_id)
    end

    @comments.each do |c|
      arrayAnchors(c, @anchors)
      userDistinction(c, @userDistinction)
    end
  end

  private

  def set_params
    @article_id = params[:article_id]
    @last_comment_id = params[:last_comment_id]
  end

  def set_anchors
    @anchors = []
    @userDistinction = []
  end

  def find_comments
    @comments = ArticleComment.includes(:article, :user).where(article_id: @article_id)
  end

  def find_articles
    @article = Article.find(@article_id)
  end
  
  def comments_params
    params.require(:article_comment).permit(:text).merge(article_id: params[:article_id],
                                                                      user_id: current_user.id)
  end

  def arrayAnchors(c, anchors)
    replies = ArticleCommentReply.where(parent_article_comment_id: c.id)
    array = []
    @repliesToCurrentUser = 0
    replies.each do |reply|
      childrenId = reply.children_article_comment_id
      children = ArticleComment.where(id: childrenId)
      children.each do |child|
      if child.user_id == current_user.id
        @repliesToCurrentUser += 1
      end
      index = child.index
        if index == nil
          array.push(nil)
        else
          array.push(index)
        end
      end
      anchors.push(array)
    end
  end

  def userDistinction(c, array)
    case c.user_id
    when current_user.id
      array.push('disabled')
    else
      array.push(nil)
    end
  end

end

app/helpers/article_comments_helper.rb
module ArticleCommentsHelper

  def myEvaluation(comment_id)
    if user_signed_in?
      evaluation = Evaluation.find_by(article_comment_id: comment_id, user_id: current_user.id)
    else
      return "blank"
    end

    if evaluation.blank?
      return "blank"
    elsif evaluation.good == 1
      return "good"
    elsif evaluation.bad == 1
      return "bad"
    end
  end

  def replyCount(id)
    reply = ArticleCommentReply.where(children_article_comment_id: id)
    return reply.length
  end

  def getReplies(id)
    a = []
    reply = ArticleCommentReply.where(children_article_comment_id: id)
    reply.each do |r|
      id = r.parent_article_comment_id
      a << ArticleComment.find(id)
    end
    return a
  end

  def form_availavility(key, myEvaluation, c)
    if myEvaluation == key || !(user_signed_in?) || current_user.id == c.user_id
      return true
    end
  end

end

app/views/article_comments/index.html.haml
= stylesheet_link_tag "articleComments", media: :all
.wrapper
  .showMain
    .content
      .article
        .article__header
          .article__header__image
            = image_tag @article.urlToImage.to_s, id: "article"
          .article__header__title{data: {article: {id: @article.id}}}
            = link_to @article.title.to_s, @article.url, target: :_blank
        .article__detail
          .article__detail__publishedAt
            = @article.publishedAt
          .article__detail__author
            = @article.author
        .article__description
          = @article.description
      = link_to "全部", article_article_comments_path(@article.id)
      = link_to "最新10", index10_article_article_comments_path(@article.id)
      = link_to "下", "#page-bottom"
      .comments
        - if @comments.present?
          - @comments.zip(@comments.ids) do |c, id|
          - myEvaluation = myEvaluation(id)
            .comment{data: {comment: {id: id}}}
              .comment__detail
                .comment__index{data: {index: c.index}}
                  = link_to "#{c.index}" + ":", "#index", class: :indexLink
                = link_to c.user.nickname, user_path(c.user.id), class: "comment__detail__nickname"
                .comment__detail__date
                  = time_setting(c.created_at)
              .comment__text
                = safe_join(c.text.split("\n"), tag(:br))
              .comment__evaluation
                .comment__evaluation__form
                  - if myEvaluation != "good"
                    = form_with url: good_evaluations_path, class: "evaluation_form_good", local: true do |f|
                      = f.hidden_field :comment_id, value: id
                      = button_tag type: 'submit', class: "good_btn", disabled: form_availavility("bad", myEvaluation, c) do
                        %i.fas.fa-thumbs-up
                          %span.count_good
                            = counting_evaluation(id, "good")
                  - else
                    = form_with url: canceling_good_evaluations_path, class: "evaluation_form_canceling_good", local: true do |f|
                      = f.hidden_field :comment_id, value: id
                      = button_tag type: 'submit', class: "canceling_good_btn" do
                        %i.fas.fa-thumbs-up
                          %span.count_good
                            = counting_evaluation(id, "good")
                .comment__evaluation__form
                  - if myEvaluation != "bad"
                    = form_with url: bad_evaluations_path, class: "evaluation_form_bad", local: true do |f|
                      = f.hidden_field :comment_id, value: id
                      = button_tag type: 'submit', class: "bad_btn", disabled: form_availavility("good", myEvaluation, c) do
                        %i.fas.fa-thumbs-down
                          %span.count_bad
                            = counting_evaluation(id, "bad")
                  - else
                    = form_with url: canceling_bad_evaluations_path, class: "evaluation_form_canceling_bad", local: true do |f|
                      = f.hidden_field :comment_id, value: id
                      = button_tag type: 'submit', class: "canceling_bad_btn" do
                        %i.fas.fa-thumbs-down
                          %span.count_bad
                            = counting_evaluation(id, "bad")
              .comment__reply#hide
                .comment__reply__btn
                  .comment__reply__text
                    返信
                  .comment__reply__count{data: {index: c.index}}
                    = replyCount(id)
                .comment__reply__content{data: {index: c.index}}
                  - if getReplies(id).present?
                    - getReplies(id).each do |c|
                      .comment#reply{data: {comment: {id: c.id}}}
                        .comment__detail
                          .comment__index{data: {index: c.index}}
                            = link_to "#{c.index}" + ":", "#index", class: :indexLink
                          = link_to c.user.nickname, user_path(c.user.id), class: "comment__detail__nickname"
                          .comment__detail__date
                            = time_setting(c.created_at)
                        .comment__text
                          = safe_join(c.text.split("\n"), tag(:br))
                        .comment__evaluation
                          .comment__evaluation__form
                            - if myEvaluation != "good"
                              = form_with url: good_evaluations_path, class: "evaluation_form_good", local: true do |f|
                                = f.hidden_field :article_id, value: @article.id
                                = f.hidden_field :comment_id, value: c.id
                                = button_tag type: 'submit', class: "good_btn", disabled: form_availavility("bad", myEvaluation, c)  do
                                  %i.fas.fa-thumbs-up
                                    %span.count_good
                                      = counting_evaluation(id, "good")
                            - else
                              = form_with url: canceling_good_evaluations_path, class: "evaluation_form_canceling_good", local: true do |f|
                                = f.hidden_field :article_id, value: @article.id
                                = f.hidden_field :comment_id, value: c.id
                                = button_tag type: 'submit', class: "canceling_good_btn" do
                                  %i.fas.fa-thumbs-up
                                    %span.count_good
                                      = counting_evaluation(c.id, "good")
                          .comment__evaluation__form
                            - if myEvaluation != "bad"
                              = form_with url: bad_evaluations_path, class: "evaluation_form_bad", local: true do |f|
                                = f.hidden_field :article_id, value: @article.id
                                = f.hidden_field :comment_id, value: c.id
                                = button_tag type: 'submit', class: "bad_btn", disabled: form_availavility("good", myEvaluation, c) do
                                  %i.fas.fa-thumbs-down
                                    %span.count_bad
                                      = counting_evaluation(c.id, "bad")
                            - else
                              = form_with url: canceling_bad_evaluations_path, class: "evaluation_form_canceling_bad", local: true do |f|
                                = f.hidden_field :article_id, value: @article.id
                                = f.hidden_field :comment_id, value: c.id
                                = button_tag type: 'submit', class: "canceling_bad_btn" do
                                  %i.fas.fa-thumbs-down
                                    %span.count_bad
                                      = counting_evaluation(c.id, "bad")
        .new_comment

      = form_with model:[@article, @article_comments], local: true, class: "comment__form", id: "new_article_comment" do |f|
        = f.text_area :text, placeholder: "コメントを入力してください", class: "text_area", cols: "60", rows: "8", maxlength: "500", disabled: !(user_signed_in?)
        = f.submit "投稿する", class: "submit_comment", disabled: !(user_signed_in?)
      = link_to "全部", article_article_comments_path(@article.id)
      = link_to "最新10", index10_article_article_comments_path(@article.id)
      = link_to "上", "#page-top"
    .alertReplies
      .alertReplies__content
        .alertReplies__content__count
          test
        .alertReplies__content__text
          件の返信

app/views/article_comments/index10.html.haml
= stylesheet_link_tag "articleComments", media: :all
.wrapper
  .showMain
    .content
      .article
        .article__header
          .article__header__image
            = image_tag @article.urlToImage.to_s, id: "article"
          .article__header__title{data: {article: {id: @article.id}}}
            = link_to @article.title.to_s, @article.url, target: :_blank
        .article__detail
          .article__detail__publishedAt
            = @article.publishedAt
          .article__detail__author
            = @article.author
        .article__description
          = @article.description
      = link_to "全部", article_article_comments_path(@article.id)
      = link_to "最新10", index10_article_article_comments_path(@article.id)
      = link_to "下", "#page-bottom"
      .comments
        - if @comments.present?
          - @comments.each do |c|
          - myEvaluation = myEvaluation(c.id)
            .comment{data: {comment: {id: c.id}}}
              .comment__detail
                .comment__index{data: {index: c.index}}
                  = link_to "#{c.index}" + ":", "#index", class: :indexLink
                = link_to c.user.nickname, user_path(c.user.id), class: "comment__detail__nickname"
                .comment__detail__date
                  = time_setting(c.created_at)
              .comment__text{data: {comment: c.id}}
                = safe_join(c.text.split("\n"), tag(:br))
              .comment__evaluation
                .comment__evaluation__form
                  - if myEvaluation != "good"
                    = form_with url: good_evaluations_path, class: "evaluation_form_good", local: true do |f|
                      = f.hidden_field :article_id, value: @article.id
                      = f.hidden_field :comment_id, value: c.id
                      = button_tag type: 'submit', class: "good_btn", disabled: form_availavility("bad", myEvaluation, c) do
                        %i.fas.fa-thumbs-up
                          %span.count_good
                            = counting_evaluation(c.id, "good")
                  - else
                    = form_with url: canceling_good_evaluations_path, class: "evaluation_form_canceling_good", local: true do |f|
                      = f.hidden_field :article_id, value: @article.id
                      = f.hidden_field :comment_id, value: c.id
                      = button_tag type: 'submit', class: "canceling_good_btn" do
                        %i.fas.fa-thumbs-up
                          %span.count_good
                            = counting_evaluation(c.id, "good")
                .comment__evaluation__form
                  - if myEvaluation != "bad"
                    = form_with url: bad_evaluations_path, class: "evaluation_form_bad", local: true do |f|
                      = f.hidden_field :article_id, value: @article.id
                      = f.hidden_field :comment_id, value: c.id
                      = button_tag type: 'submit', class: "bad_btn", disabled: form_availavility("good", myEvaluation, c) do
                        %i.fas.fa-thumbs-down
                          %span.count_bad
                            = counting_evaluation(c.id, "bad")
                  - else
                    = form_with url: canceling_bad_evaluations_path, class: "evaluation_form_canceling_bad", local: true do |f|
                      = f.hidden_field :article_id, value: @article.id
                      = f.hidden_field :comment_id, value: c.id
                      = button_tag type: 'submit', class: "canceling_bad_btn" do
                        %i.fas.fa-thumbs-down
                          %span.count_bad
                            = counting_evaluation(c.id, "bad")
              .comment__reply#hide
                .comment__reply__btn
                  .comment__reply__text
                    返信
                  .comment__reply__count{data: {index: c.index}}
                    = replyCount(c.id)
                .comment__reply__content
                  - if getReplies(c.id).present?
                    - getReplies(c.id).each do |c|
                      .comment.reply{data: {comment: {id: c.id}}}
                        .comment__detail
                          .comment__index{data: {index: c.index}}
                            = "#{c.index}" + ":"
                          = link_to c.user.nickname, user_path(c.user.id), class: "comment__detail__nickname"
                          .comment__detail__date
                            = time_setting(c.created_at)
                        .comment__text
                          = safe_join(c.text.split("\n"), tag(:br))
                        .comment__evaluation
                          .comment__evaluation__form
                            - if myEvaluation != "good"
                              = form_with url: good_evaluations_path, class: "evaluation_form_good", local: true do |f|
                                = f.hidden_field :article_id, value: @article.id
                                = f.hidden_field :comment_id, value: c.id
                                = button_tag type: 'submit', class: "good_btn", disabled: form_availavility("bad", myEvaluation, c) do
                                  %i.fas.fa-thumbs-up
                                    %span.count_good
                                      = counting_evaluation(c.id, "good")
                            - else
                              = form_with url: canceling_good_evaluations_path, class: "evaluation_form_canceling_good", local: true do |f|
                                = f.hidden_field :article_id, value: @article.id
                                = f.hidden_field :comment_id, value: c.id
                                = button_tag type: 'submit', class: "canceling_good_btn" do
                                  %i.fas.fa-thumbs-up
                                    %span.count_good
                                      = counting_evaluation(c.id, "good")
                          .comment__evaluation__form
                            - if myEvaluation != "bad"
                              = form_with url: bad_evaluations_path, class: "evaluation_form_bad", local: true do |f|
                                = f.hidden_field :article_id, value: @article.id
                                = f.hidden_field :comment_id, value: c.id
                                = button_tag type: 'submit', class: "bad_btn", disabled: form_availavility("good", myEvaluation, c) do
                                  %i.fas.fa-thumbs-down
                                    %span.count_bad
                                      = counting_evaluation(c.id, "bad")
                            - else
                              = form_with url: canceling_bad_evaluations_path, class: "evaluation_form_canceling_bad", local: true do |f|
                                = f.hidden_field :article_id, value: @article.id
                                = f.hidden_field :comment_id, value: c.id
                                = button_tag type: 'submit', class: "canceling_bad_btn" do
                                  %i.fas.fa-thumbs-down
                                    %span.count_bad
                                      = counting_evaluation(c.id, "bad")
        .new_comment

      = form_with model:[@article, @article_comments], local: true, class: "comment__form", id: "new_article_comment" do |f|
        = f.text_area :text, placeholder: "コメントを入力してください", class: "text_area", cols: "60", rows: "8", maxlength: "500", disabled: !(user_signed_in?)
        = f.submit "投稿する", class: "submit_comment", disabled: !(user_signed_in?)
      = link_to "全部", article_article_comments_path(@article.id)
      = link_to "最新10", index10_article_article_comments_path(@article.id)
      = link_to "上", "#page-top"
    .alertReplies
      .alertReplies__content
        .alertReplies__content__count
          test
        .alertReplies__content__text
          件の返信

app/views/article_comments/show.html.haml
= stylesheet_link_tag "articleComments", media: :all
.wrapper
  .showMain
    .content
      .article
        .article__header
          .article__header__image
            = image_tag @article.urlToImage.to_s, id: "article"
          .article__header__title{data: {article: {id: @article.id}}}
            = link_to @article.title.to_s, @article.url, target: :_blank
        .article__detail
          .article__detail__publishedAt
            = @article.publishedAt
          .article__detail__author
            = @article.author
        .article__description
          = @article.description
      = link_to "全部", article_article_comments_path(@article.id)
      = link_to "最新10", index10_article_article_comments_path(@article.id)
      = link_to "下", "#page-bottom"
      .comments
        - if @comment.present?
        - c = @comment
        - id = @comment.id
        - myEvaluation = myEvaluation(id)
          .comment{data: {comment: {id: id}}}
            .comment__detail
              .comment__index{data: {index: c.index}}
                = link_to "#{c.index}" + ":", "#index", class: :indexLink
              = link_to c.user.nickname, user_path(c.user.id), class: "comment__detail__nickname"
              .comment__detail__date
                = time_setting(c.created_at)
            .comment__text{data: {comment: id}}
              = safe_join(c.text.split("\n"), tag(:br))
            .comment__evaluation
              .comment__evaluation__form
                - if myEvaluation != "good"
                  = form_with url: good_evaluations_path, class: "evaluation_form_good", local: true do |f|
                    = f.hidden_field :comment_id, value: id
                    = button_tag type: 'submit', class: "good_btn", disabled: form_availavility("bad", myEvaluation, c) do
                      %i.fas.fa-thumbs-up
                        %span.count_good
                          = counting_evaluation(id, "good")
                - else
                  = form_with url: canceling_good_evaluations_path, class: "evaluation_form_canceling_good", local: true do |f|
                    = f.hidden_field :comment_id, value: id
                    = button_tag type: 'submit', class: "canceling_good_btn" do
                      %i.fas.fa-thumbs-up
                        %span.count_good
                          = counting_evaluation(id, "good")
              .comment__evaluation__form
                - if myEvaluation != "bad"
                  = form_with url: bad_evaluations_path, class: "evaluation_form_bad", local: true do |f|
                    = f.hidden_field :comment_id, value: id
                    = button_tag type: 'submit', class: "bad_btn", disabled: form_availavility("good", myEvaluation, c) do
                      %i.fas.fa-thumbs-down
                        %span.count_bad
                          = counting_evaluation(id, "bad")
                - else
                  = form_with url: canceling_bad_evaluations_path, class: "evaluation_form_canceling_bad", local: true do |f|
                    = f.hidden_field :comment_id, value: id
                    = button_tag type: 'submit', class: "canceling_bad_btn" do
                      %i.fas.fa-thumbs-down
                        %span.count_bad
                          = counting_evaluation(id, "bad")
            .comment__reply#hide
              .comment__reply__btn
                .comment__reply__text
                  返信
                .comment__reply__count{data: {index: c.index}}
                  = replyCount(id)
              .comment__reply__content{data: {index: c.index}}
                - if getReplies(id).present?
                  - getReplies(id).each do |c|
                    .comment#reply{data: {comment: {id: id}}}
                      .comment__detail
                        .comment__index{data: {index: c.index}}
                          = link_to "#{c.index}" + ":", "#index", class: :indexLink
                        = link_to c.user.nickname, user_path(c.user.id), class: "comment__detail__nickname"
                        .comment__detail__date
                          = time_setting(c.created_at)
                      .comment__text
                        = safe_join(c.text.split("\n"), tag(:br))
                      .comment__evaluation
                        .comment__evaluation__form
                          - if myEvaluation != "good"
                            = form_with url: good_evaluations_path, class: "evaluation_form_good", local: true do |f|
                              = f.hidden_field :article_id, value: @article.id
                              = f.hidden_field :comment_id, value: c.id
                              = button_tag type: 'submit', class: "good_btn", disabled: form_availavility("bad", myEvaluation, c)  do
                                %i.fas.fa-thumbs-up
                                  %span.count_good
                                    = counting_evaluation(id, "good")
                          - else
                            = form_with url: canceling_good_evaluations_path, class: "evaluation_form_canceling_good", local: true do |f|
                              = f.hidden_field :article_id, value: @article.id
                              = f.hidden_field :comment_id, value: c.id
                              = button_tag type: 'submit', class: "canceling_good_btn" do
                                %i.fas.fa-thumbs-up
                                  %span.count_good
                                    = counting_evaluation(c.id, "good")
                        .comment__evaluation__form
                          - if myEvaluation != "bad"
                            = form_with url: bad_evaluations_path, class: "evaluation_form_bad", local: true do |f|
                              = f.hidden_field :article_id, value: @article.id
                              = f.hidden_field :comment_id, value: c.id
                              = button_tag type: 'submit', class: "bad_btn", disabled: form_availavility("good", myEvaluation, c) do
                                %i.fas.fa-thumbs-down
                                  %span.count_bad
                                    = counting_evaluation(c.id, "bad")
                          - else
                            = form_with url: canceling_bad_evaluations_path, class: "evaluation_form_canceling_bad", local: true do |f|
                              = f.hidden_field :article_id, value: @article.id
                              = f.hidden_field :comment_id, value: c.id
                              = button_tag type: 'submit', class: "canceling_bad_btn" do
                                %i.fas.fa-thumbs-down
                                  %span.count_bad
                                    = counting_evaluation(c.id, "bad")
        .new_comment
      .showAction
      = link_to "全部", article_article_comments_path(@article.id), id: :showAction
      = link_to "最新10", index10_article_article_comments_path(@article.id)
      = link_to "上", "#page-top"
    .alertReplies
      .alertReplies__content
        .alertReplies__content__count
          test
        .alertReplies__content__text
          件の返信