config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root 'articles#index'
  resources :users, only: [:show]
  resources :groups, only: [:index, :show, :create] do
    member do
      get :api, defaults: { format: 'json' }
    end
  end
  resources :comments, only: [:create]
  resources :favorites, only: [:create] do
    collection do
      post :api, defaults: { format: 'json' }
    end
  end
  resources :articles, only: [:index, :show] do
    resources :article_comments, only: [:index, :show, :create] do
      collection do
        get :index10
        get :api, defaults: {format: 'json'}
      end
    end
  end
  resources :evaluations do
    collection do 
      post :good
      post :bad
      post :canceling_good
      post :canceling_bad
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :article_comments

  def self.createArticles(key)
    unless self.exists?(key)
      self.create(key)
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_secretKey
  before_action :set_articleComments
  require 'news-api'

  def index
    @news = @News.get_top_headlines(country: 'jp')
    create_articles
  end

  def show
    category = view_context.categoryArray
    @news = @News.get_top_headlines(country: 'jp',
                                    category: category[params[:id].to_i])
    create_articles
  end

  private

  def set_secretKey
    @News = News.new(ENV['NEWS_API_PRIVATE_KEY'])
  end
  
  def create_articles
    @news.each do |n|
      if n.author == "netkeiba.com"
        Article.createArticles(title: n.title, url: n.url, author: n.author, publishedAt: n.publishedAt, urlToImage: n.urlToImage)
      else
        Article.createArticles(title: n.title, url: n.url, description: n.description, author: n.author, publishedAt: n.publishedAt, urlToImage: n.urlToImage)
      end
    end
  end

  def set_articleComments
    @articleComments = ArticleComment.order('id DESC').limit(20)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  def categoryArray
    ["entertainment", "general", "health", "science", "sports", "technology"]
  end

  def categoryArrayjp
    ["エンタメ", "一般", "健康", "科学", "スポーツ", "テクノロジー"]
  end

  def articleID(a)
    article = Article.where(title: a.title, url: a.url)
    return article.ids
  end

  def article_comment(id)
    comments = ArticleComment.where(article_id: id)
    case comments
    when nil
      return "0"
    else
      return comments.length
    end
  end

end

app/views/articles/index.html.haml
= stylesheet_link_tag "articles", media: :all
.wrapper
  .showMain
    .content
      .content__top
        .content__top__category#headLine
          = link_to "ヘッドライン", articles_path, class: "categoryArray"
        - categoryArrayjp.zip(0..5) do |category, i|
          .content__top__category{id: i}
            = link_to category, article_path(i), class: "categoryArray"
      .content__main
        .content__main__left
          - @news.each do |n|
            .article
              .article__left
                = image_tag n.urlToImage.to_s
              .article__right
                .article__right__title
                  = link_to n.title.gsub(/-.+$/, ""), n.url.to_s, target: :_blank
                .article__right__bottom
                  .article__right__bottom__author
                    = n.title.match(/[^-]+$/)
                  .article__right__bottom__commentCounts
                    = link_to "コメント", article_article_comments_path(articleID(n))
                    .article__right__bottom__commentCounts__number
                      = article_comment(articleID(n))
        .content__main__right
          .content__main__right__header
            新着コメント
          .articleComments
            - @articleComments.each do |c|
              .articleComment
                .articleComment__text
                  = c.text.truncate(40)
                .articleComment__articleTitle
                  = link_to articleTitle(c.article_id).truncate(20), articlePath(c.article_id)

app/views/articles/show.html.haml
= stylesheet_link_tag "articles", media: :all
.wrapper
  .showMain
    .content
      .content__top
        .content__top__category#headLine
          = link_to "ヘッドライン", articles_path, class: "categoryArray"
        - categoryArrayjp.zip(0..5) do |category, i|
          .content__top__category{id: i}
            = link_to category, article_path(i), class: "categoryArray"
      .content__main
        .content__main__left
          - @news.each do |n|
            .article
              .article__left
                = image_tag n.urlToImage.to_s
              .article__right
                .article__right__title
                  = link_to n.title.gsub(/-.+$/, ""), n.url.to_s, target: :_blank
                .article__right__bottom
                  .article__right__bottom__author
                    = n.title.match(/[^-]+$/)
                  .article__right__bottom__commentCounts
                    = link_to "コメント", article_article_comments_path(articleID(n))
                    .article__right__bottom__commentCounts__number
                      = article_comment(articleID(n))
        .content__main__right
          .content__main__right__header
            新着コメント
          .articleComments
            - @articleComments.each do |c|
              .articleComment
                .articleComment__text
                  = c.text.truncate(40)
                .articleComment__articleTitle
                  = link_to articleTitle(c.article_id).truncate(20), articlePath(c.article_id)