config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root 'articles#index'
  resources :users, only: [:show]
  resources :groups, only: [:index, :show, :create] do
    member do
      get :api, defaults: { format: 'json' }
    end
  end
  resources :comments, only: [:create]
  resources :favorites, only: [:create] do
    collection do
      post :api, defaults: { format: 'json' }
    end
  end
  resources :articles, only: [:index, :show] do
    resources :article_comments, only: [:index, :show, :create] do
      collection do
        get :index10
        get :api, defaults: {format: 'json'}
      end
    end
  end
  resources :evaluations do
    collection do 
      post :good
      post :bad
      post :canceling_good
      post :canceling_bad
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :article_comments
  has_many :evaluations

  validates :nickname, presence: true, length: {maximum: 8}
  validates :email, presence: true
  validates :password, presence: true

  def remember_me
    true
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @evaluations = Evaluation.where(children_user_id: params[:id])
    @good = @evaluations.where(good: 1).length
    @bad = @evaluations.where(bad: 1).length
    @articleComments = ArticleComment.where(user_id: params[:id]).order("created_at DESC").limit(10)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def rate(good, bad)
    denominator = (good + bad)
    if denominator != 0
      rate =  (good.to_f / denominator) * 100
      return rate.round(1)
    else
      return "---"
    end
  end

end

app/views/users/show.html.haml
= stylesheet_link_tag "users", media: :all
.wrapper
  .content
    .content__header
      .content__header__nickname
        = @user.nickname
      .content__header__text
        さんのマイページ
    .mainItem
      .mainItem__left
        .mainItem__left__header
          最新コメント10件
        .mainItem__left__content
          - @articleComments.each do |c|
            .mainItem__left__content__comment
              .mainItem__left__content__comment__detail
                .mainItem__left__content__comment__detail__date
                  = time_setting(c.created_at)
                .mainItem__left__content__comment__detail__evaluation
                  %i.fas.fa-thumbs-up
                    %span.mainItem__left__content__comment__detail__evaluation__good
                      = counting_evaluation(c.id, "good")
                  %i.fas.fa-thumbs-down
                    %span.mainItem__left__content__comment__detail__evaluation__bad
                      = counting_evaluation(c.id, "bad")
              .mainItem__left__content__comment__text
                = link_to c.text.truncate(58), article_article_comment_path(c.article_id, c.id)
              .mainItem__left__content__comment__articleTitle
                = link_to articleTitle(c.article_id).truncate(20), articlePath(c.article_id)
      .mainItem__right
        .mainItem__right__count
          .mainItem__right__count__good
            = "高評価 #{@good.to_s} (#{rate(@good, @bad)}%)"
          .mainItem__right__count__bad
            = "低評価  " + @bad.to_s
        .mainItem__right__graph
          = pie_chart [["低評価", @bad], ["高評価", @good]], colors: ["#F02040", "#2040F0"]